### PR TITLE
Remove unused levels in dudi functions (and others)

### PR DESCRIPTION
**Pull request by CeresBarros**
Proposed fix to issue #11 :
When using categorical (factor or ordered in dudi.mix) arguments, there is now a check that removes unused levels if there are any.

### CODE REVIEW

**Comment by CeresBarros** [comment]
HI there, 
Will you merge this PR into master? Or have you corrected this in another way? 
Thanks!

**Comment by sdray** [comment]
Hi Ceres

As I said in a previous message, I should check that other functions (e.g., plots, summary methods) are not affected by this change. As we are very busy (we should finish the writing of a book on ade4 this week), we did not yet test your changes.. But we will do it soon and include these changes in the next release of ade4 if it is ok.

Sorry for the delay!

**Comment by CeresBarros** [comment]
Oh, sorry I forgot about your last message! Thanks for letting me know :)

**Comment by sdray** [comment]
Hi Ceres. After checking ade4 and our other packages, I found that your changes break several other functions (e.g., plot functions). As we do not have tests for all functions, I prefer to not include your changes. Moreover, I think that this task could/should be done before running the analyses by applying droplevels function on objects. 

Cheers

**Comment by CeresBarros** [comment]
If I ever have some time on my hands I might try to look into that. I understand that this can be achieved by the user before running ade4 functions, but I felt that the error wasn't very clear. Perhaps throwing a more informative error message would help? 

In any case, thanks for the feedback and sorry that the changes broke plotting!

**Pull request closed without merging**
